version: 2.1

orbs:
  cloudesire: cloudesire/common@0

defaults: &defaults
  environment:
    BASE_BUILD_NUM: "0"
  executor:
    name: cloudesire/docker_java

jobs:
  build:
    <<: *defaults

    steps:
    - checkout

    - run:
        name: Get common configs
        command: git clone git@github.com:ClouDesire/ci-conf.git ~/repo/conf

    - restore_cache:
        keys:
        - m2-{{ checksum "server/pom.xml" }}
        - m2-

    - run:
        name: Setup artifactory
        command: mkdir -p ~/.m2 && cp ~/repo/conf/mvn/settings.xml ~/.m2

    - run:
        name: Build
        command: ./mvnw -B verify

    - save_cache:
        key: m2-{{ checksum "server/pom.xml" }}
        paths:
        - "~/.m2"

    - setup_remote_docker

    - run:
        name: Build Docker Image
        command: cd server && ~/repo/conf/mvn/docker-build.sh

    - deploy:
        name: Upload client
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            ./mvnw -B deploy -Dmaven.test.skip=true -pl client
          fi

    - deploy:
        name: Upload Docker Image
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            ~/repo/conf/mvn/docker-upload.sh
          fi

workflows:
  build-and-deploy:
    jobs:
      - build:
          context:
            - common-not-really-secrets
            - common-github
            - common-archiva
