version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8u151-jdk
      environment:
      - BASE_BUILD_NUM: 0

    environment:
      MAVEN_OPTS: "-Xmx2048m"

    steps:
    - checkout

    - run:
        name: Get common configs
        command: git clone git@github.com:ClouDesire/ci-conf.git ~/repo/conf

    - restore_cache:
        keys:
        - m2-{{ checksum "server/pom.xml" }}
        - m2-

    - run:
        name: Setup artifactory
        command: mkdir -p ~/.m2 && cp ~/repo/conf/mvn/settings.xml ~/.m2

    - run:
        name: Build
        command: ./mvnw -B verify

    - save_cache:
        key: m2-{{ checksum "server/pom.xml" }}
        paths:
        - "~/.m2"

    - setup_remote_docker

    - run:
        name: Build Docker Image
        command: cd server && ~/repo/conf/mvn/docker-build.sh

    - deploy:
        name: Upload Docker Image
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            ~/repo/conf/mvn/docker-upload.sh
          fi
